language: php

php:
    - "5.6"
    - "5.5"
    - "5.4"

script:
    - ant -f build/build.xml -Ddb.user=travis -Ddb.host=127.0.0.1 -Ddb.name=shopware build-continuous static-lint

notifications:
    email: false
