imports:
    - { resource: shopware.yml }

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ['!event']
        console:
            type:   console
            channels: ['!event', '!doctrine']

parameters:
    swag_test.param1: 1000

#framework:
#    cache:
#        app: cache.adapter.apcu